### PR TITLE
Updates for general image

### PR DESCRIPTION
**Pull request by jaguillette**
This PR updates the general image, and also switches over from the `harvardat` docker org to the `huitacademictechnology` org. This is because the `harvardat` org is a free tier org that was set up early on for expedience, but since then we have created a new org that is a licensed org.

The updates for the general image include bumping up the version of the base image, removing packages that were requested specifically by fall term courses, and re-creating the requirements.txt file from requirements.in to bump up package versions.

The new image can be pulled with

```
docker pull huitacademictechnology/fas-jupyter-general:sha-3eb8c9b
```

### CODE REVIEW

**Review by arthurian — APPROVED** [review]
Looks good! 👍

**Review by Tanvez — APPROVED** [review]
LGTM!

**Review by wrobind — APPROVED** [review]
The changes appear to match the description. I have questions about how large-scale changes, especially deletions, in the requirements.txt files are controlled and tracked, but that's more a startled reaction than a review comment.

**Comment by jaguillette** [comment]
Good point, Robin. The `requirements.txt` file and the `environment.yml` file are both downstream of `requirements.in`, which is where we make explicit changes to requirements based on course requests. Since I removed 5 libraries that were requested last semester, but not this semester, a whole slew of their dependencies were removed. `requirements.txt` is generated by `pip-compile` before building the image, and `environment.yml` is generated post-build as a reference for what libraries are installed, regardless of whether they come from pip, conda, or the base image.

**Pull request merged**
